# Generated by Django 5.0.4 on 2024-07-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='recepie_description',
            new_name='receipe_description',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='recepie_image',
            new_name='receipe_image',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='recepie_name',
            new_name='receipe_name',
        ),
    ]
